language: node_js

node_js:
  - 10.14

before_install:
  - nvm install node
  - npm install -g npm@latest

install:
  - npm install

script:
  - grunt
  - grunt doc

deploy:
  provider: pages
  local-dir: doc
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  on:
    branch: master
