language: node_js

node_js:
  - 10.14

before_install:
  - nvm install node
  - npm install -g npm@latest

install:
  - npm install

script:
  - grunt
  - grunt doc
  - mkdir deploy deploy/build
  - zip build/sam.zip build/sam.css build/sam.min.js
  - mv build/sam.zip build/sam.css build/sam.min.js deploy/build
  - mv doc deploy/docs

deploy:
  provider: pages
  local-dir: deploy
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  on:
    branch: master
